# Generated by Django 5.2 on 2025-04-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_alter_mediafile_options_mediafile_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='yolo_detections',
            field=models.JSONField(blank=True, null=True, verbose_name='Данные обнаружения'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='yolo_processed',
            field=models.BooleanField(default=False, verbose_name='Обработано YOLO'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='yolo_result_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к обработанному файлу'),
        ),
    ]
