# Generated by Django 5.2 on 2025-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_mediafile_yolo_detections_mediafile_yolo_processed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediafile',
            name='yolo_detections',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='yolo_processed',
        ),
        migrations.RemoveField(
            model_name='mediafile',
            name='yolo_result_path',
        ),
        migrations.AddField(
            model_name='mediafile',
            name='yolo_objects',
            field=models.JSONField(blank=True, null=True, verbose_name='Обнаруженные объекты'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='yolo_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время обработки YOLO'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='yolo_processed_file',
            field=models.FileField(blank=True, null=True, upload_to='yolo_results/', verbose_name='Файл с разметкой YOLO'),
        ),
    ]
