# Generated by Django 5.2 on 2025-04-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Медиафайл', 'verbose_name_plural': 'Медиафайлы'},
        ),
        migrations.AddField(
            model_name='mediafile',
            name='duration',
            field=models.FloatField(blank=True, help_text='Для видеофайлов', null=True, verbose_name='Длительность (сек)'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='completed', max_length=20, verbose_name='Статус обработки'),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео')], max_length=10, verbose_name='Тип файла'),
        ),
    ]
